apiVersion: v1
kind: Service
metadata:
  name: horsefly-userportal-service
spec:
  ports:
    - port: REPLACE-WITH-PORT-TO-FOWARD-TO-30000-32767
      nodePort: SAME-PORT-NUMBER-AS-ABOVE
      targetPort: horsefly-userportal-port
      protocol: TCP
  selector:
    app: horsefly-userportal
  type: NodePort
